name: ci

on:
  push:
    branches:
      - master

jobs:
  test:
    name: molecule-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Install dependencies
        run: |
          pip3 install molecule docker ansible

      - name: Run Molecule tests
        run: molecule test -s roles/web_server/molecule/default
