name: ci

on:
  push:
    branches:
      - main

jobs:
  test:
    name: molecule-test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./roles/web_server

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip3 install molecule docker 
          pip3 install molecule-plugins[docker] 

      - name: Run Molecule tests
        run: molecule test
